apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: ekscluster.zicong.com
spec:
  group: zicong.com
  names:
    kind: EksCluster
    plural: ekscluster
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                  k8sVersion:
                    type: string
                required:
                - region
            required:
            - parameters
          status:
            type: object
            description: A AttachedClusterStatus represents the observed state of
              a Cluster.
            properties:
              cluster:
                type: string
              clusterName:
                type: string
              clusterSelfLink:
                type: string
              controlPlaneStatus:
                type: string
              membershipId:
                type: string
              nodePoolStatus:
                type: string
              odicIssuerUrl:
                type: string
