apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: eksattached.zicong.com
spec:
  group: zicong.com
  names:
    kind: EksAttached
    plural: eksattached
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                required:
                - region
            required:
            - parameters
          status:
            type: object
            properties:
              vpcId:
                description: "VPC ID"
                type: string
              privateSubnetId:
                description: "private subnet ID"
                type: string